-- =====================================================
-- CREATE DISPATCHERS WITH SUPABASE AUTH INTEGRATION
-- =====================================================
-- This script inserts new dispatchers with proper UUIDs that will
-- match their Supabase Auth user IDs for secure communication.
-- 
-- IMPORTANT: Run the Node.js migration script FIRST to create
-- Supabase Auth users, then run this SQL to insert dispatcher records.
-- =====================================================

-- Insert dispatcher records with UUIDs that match Supabase Auth users
-- These UUIDs were generated by the Node.js script and match the actual Supabase Auth user IDs
-- IMPORTANT: These are the real UUIDs from the auth users that were just created

INSERT INTO dispatchers (
    id,                    -- This UUID must match the Supabase Auth user ID
    station_id,            -- Station ID (FS001, FS002, etc.)
    dispatcher_id,         -- This is a TEXT field that must be unique
    name,                  -- Dispatcher name
    email,
    phone,
    region,                -- Region name (NOT NULL)
    password,
    is_active,             -- Active status
    created_at,
    updated_at,
    latitude,
    longitude
) VALUES 
-- Accra Central Station (Kwame Asante)
('8e66c8dd-26f7-4f92-858d-0f68a7957e5b', 'FS001', 'FS001DISP01', 'Kwame Asante', 'dispatch.accracentral@gmail.com', '+233 24 123 4567', 'Greater Accra Region', 'FireStation101!', true, NOW(), NOW(), 5.6034, -0.1870),

-- Takoradi Station (Kofi Mensah)
('74ef3d95-7904-49e3-ae32-013dd0e13cfb', 'FS003', 'FS003DISP01', 'Kofi Mensah', 'dispatch.takoradi@gmail.com', '+233 26 345 6789', 'Western Region', 'FireStation103!', true, NOW(), NOW(), 4.9020, -1.7608),

-- Tamale Station (Fatima Abdul)
('d48ca1e0-f82c-4e63-ab5d-c4ed22c801bf', 'FS004', 'FS004DISP01', 'Fatima Abdul', 'dispatch.tamale@gmail.com', '+233 27 456 7890', 'Northern Region', 'FireStation104!', true, NOW(), NOW(), 9.4035, -0.8423),

-- Tema Station (Yaw Darko)
('681a68bc-19e8-4fe1-9e69-d5aaec986a8c', 'FS005', 'FS005DISP01', 'Yaw Darko', 'dispatch.tema@gmail.com', '+233 28 567 8901', 'Greater Accra Region', 'FireStation105!', true, NOW(), NOW(), 5.6833, -0.0167),

-- Cape Coast Station (Efua Addo)
('a5ac14d7-a35c-4113-8f00-cea8716a97ce', 'FS006', 'FS006DISP01', 'Efua Addo', 'dispatch.capecoast@gmail.com', '+233 29 678 9012', 'Central Region', 'FireStation106!', true, NOW(), NOW(), 5.1053, -1.2466),

-- Koforidua Station (Kwesi Boateng)
('d9d1541b-8ec3-446c-8b4c-5f95613d2575', 'FS007', 'FS007DISP01', 'Kwesi Boateng', 'dispatch.koforidua@gmail.com', '+233 30 789 0123', 'Eastern Region', 'FireStation107!', true, NOW(), NOW(), 6.1043, -0.2613),

-- Sunyani Station (Abena Sarpong)
('056d7088-aec7-4b34-8ec9-e4728dd8a811', 'FS008', 'FS008DISP01', 'Abena Sarpong', 'dispatch.sunyani@gmail.com', '+233 31 890 1234', 'Bono Region', 'FireStation108!', true, NOW(), NOW(), 7.3399, -2.3268),

-- Ho Station (Kweku Agyeman)
('1f875fce-db01-47af-bfc7-ae44d70a1d85', 'FS009', 'FS009DISP01', 'Kweku Agyeman', 'dispatch.ho@gmail.com', '+233 32 901 2345', 'Volta Region', 'FireStation109!', true, NOW(), NOW(), 6.6038, 0.4710),

-- Bolgatanga Station (Aisha Mohammed)
('38e8046f-ae3c-4f52-bb22-fc26fcf00ca4', 'FS010', 'FS010DISP01', 'Aisha Mohammed', 'dispatch.bolgatanga@gmail.com', '+233 33 012 3456', 'Upper East Region', 'FireStation110!', true, NOW(), NOW(), 10.7854, -0.8513);

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
-- Run these queries to verify the dispatchers were created successfully:

-- Check how many dispatchers were inserted
SELECT COUNT(*) as total_dispatchers FROM dispatchers;

-- View all dispatchers with their details
SELECT 
    id,
    name,
    email,
    phone,
    station_id,
    region,
    latitude,
    longitude,
    created_at
FROM dispatchers
ORDER BY name;

-- Check if dispatchers have valid UUIDs (should match auth.users)
SELECT 
    d.id as dispatcher_id,
    d.name,
    d.email,
    d.station_id,
    d.region,
    CASE 
        WHEN au.id IS NOT NULL THEN 'Auth User Exists'
        ELSE 'NO AUTH USER - NEEDS FIXING'
    END as auth_status
FROM dispatchers d
LEFT JOIN auth.users au ON d.id = au.id
ORDER BY d.name; 